# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
